spring:
  application:
    name: finguide-be
  datasource:
    url: ${FINGUIDE_DATASOURCE_URL:jdbc:h2:mem:${random.uuid};MODE=PostgreSQL;DATABASE_TO_UPPER=false}
    username: ${FINGUIDE_DATASOURCE_USERNAME:sa}
    password: ${FINGUIDE_DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: ${FINGUIDE_H2_CONSOLE_ENABLED:true}
      path: /h2-console
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/finguide}

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  servlet:
    context-path: /finguide-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: ${FINGUIDE_SWAGGER_CONFIG_URL:/v3/api-docs/swagger-config}
    url: ${FINGUIDE_SWAGGER_API_DOCS_URL:/v3/api-docs}
  api-docs:
    path: /v3/api-docs

finguide:
  security:
    demo-mode: ${FINGUIDE_DEMO_MODE:true}
    required-audience: ${KEYCLOAK_AUDIENCE:finguide-api}
